name: 'Publish'
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLATPAK_ID: com.gitbutler.app

jobs:
  bundle-flatpak:
    runs-on: ubuntu-24.04
    # container:
    #   image: bilelmoussaoui/flatpak-github-actions:gnome-47
    #   options: --privileged
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Prerequisites
        run: |
          sudo apt update && \
            sudo apt install -yqq flatpak flatpak-builder appstream-compose
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak install --user --noninteractive flathub org.gnome.Platform//47 org.gnome.Sdk//47

      - name: Build Flatpak
        run: |
          flatpak-builder --user --repo=repo --force-clean --install-deps-from=flathub build-dir com.gitbutler.app.yml

      - name: Create Flatpak bundle
        run: |
          flatpak build-bundle repo ${{ env.FLATPAK_ID }}.flatpak ${{ env.FLATPAK_ID }}

      - name: Archive Flatpak files
        run: |
          mkdir flatpak_output
          cp ${{ env.FLATPAK_ID }}.flatpak flatpak_output/
          cp com.gitbutler.app.yml flatpak_output/
          tar -czvf gitbutler_flatpak.tar.gz flatpak_output

      - name: Upload Flatpak archive
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-archive
          path: gitbutler_flatpak.tar.gz
